-- Add `group_continue_requests` to the `supabase_realtime` publication.
--
-- 0043 created the table but didn't `ALTER PUBLICATION supabase_realtime
-- ADD TABLE`. The iOS conv-level Realtime channel registers
-- postgres_changes filters for it (used to surface / dismiss the group
-- continue-vote banner without polling). Supabase Realtime's server
-- behaviour for an unpublished table is the trap here: it accepts the
-- channel join with status=ok, then silently drops events for *every*
-- postgres_changes filter on the same channel — including `messages`.
--
-- Surfaces as: in user_user (and group) chats, the recipient sees the
-- conv-list preview update via the user-level `user_unread_counts`
-- channel (separate channel, unaffected) but never sees new messages
-- arrive in the open conversation view. Re-entering the chat shows
-- them only because `loadHistory()` re-fetches over REST.
ALTER PUBLICATION supabase_realtime ADD TABLE pendingbot.group_continue_requests;
